name: Run NodePay Script

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'

      - name: Install Playwright and Chromium
        run: |
          npm install playwright
          npx playwright install --with-deps chromium

      - name: Install Xvfb (Simulate GUI for headless false)
        run: sudo apt update && sudo apt install -y xvfb

      - name: Clear old NodePay profile
        run: rm -rf /home/runner/Nodepay/nodepay_1

      - name: Clear old extension files
        run: rm -rf /home/runner/Nodepay/extension

      - name: Extract Chromium Profile
        run: |
          mkdir -p /home/runner/Nodepay/nodepay_1
          tar -xzvf nodepay-profile.tar.gz -C /home/runner/Nodepay/nodepay_1

      - name: Extract Extension
        run: |
          mkdir -p /home/runner/Nodepay/extension
          tar -xzvf extension-profile.tar.gz -C /home/runner/Nodepay/extension

      - name: Start Xvfb (Enable GUI for Playwright)
        run: Xvfb :99 -screen 0 1920x1080x24 & sleep 3

      - name: Run NodePay script
        run: node nodepay.js
        env:
          DISPLAY: ':99.0'  # Use virtual display
          PLAYWRIGHT_BROWSERS_PATH: 0  # Ensure Playwright installs a fresh browser
          PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS: 1  # Bypass Playwright system checks
