name: Run NodePay Script

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'

      - name: Install Playwright
        run: npm install playwright && npx playwright install chromium

      - name: Install Xvfb (Simulate GUI for headless false)
        run: sudo apt update && sudo apt install -y xvfb

      - name: Clear old NodePay profile
        run: rm -rf /home/runner/Nodepay/nodepay_1

      - name: Clear old extension files
        run: rm -rf /home/runner/Nodepay/extension

      - name: Extract Chromium Profile
        run: |
          mkdir -p /home/runner/Nodepay/nodepay_1
          tar -xzvf nodepay-profile.tar.gz -C /home/runner/Nodepay/nodepay_1

      - name: Extract Extension
        run: |
          mkdir -p /home/runner/Nodepay/extension
          tar -xzvf extension.tar.gz -C /home/runner/Nodepay/extension
          echo "Listing extracted files in /home/runner/Nodepay/extension:"
          ls -R /home/runner/Nodepay/extension

      - name: Detect Correct Extension Path
        run: |
          EXT_PATH=$(find /home/runner/Nodepay/extension -maxdepth 1 -type d | grep -E '[0-9]+\.[0-9]+_[0-9]+$' || echo "")
          if [[ -z "$EXT_PATH" ]]; then
            echo "Error: No valid extension folder found!" >&2
            exit 1
          fi
          echo "Detected Extension Path: $EXT_PATH"
          echo "EXTENSION_PATH=$EXT_PATH" >> $GITHUB_ENV

      - name: Start Xvfb (Enable GUI for Playwright)
        run: Xvfb :99 -screen 0 1920x1080x24 & sleep 3

      - name: Run NodePay script
        run: node nodepay.js
        env:
          DISPLAY: ':99.0'  # Use virtual display
          PLAYWRIGHT_BROWSERS_PATH: 0  # Ensure Playwright installs a fresh browser
          EXTENSION_PATH: ${{ env.EXTENSION_PATH }}  # Pass detected extension path to the script
