name: Run Predict-bot Script

on:
  workflow_dispatch:

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run automation script
        run: node flashscore.js  # Runs the script directly with Node.js
        env:
          DISPLAY: ':99.0'  # Enable Xvfb to run headless

      - name: Upload match screenshot
        uses: actions/upload-artifact@v4
        with:
          name: match-data
          path: matches.txt
