const { chromium } = require('playwright');

(async () => { const browser = await chromium.launch({ headless: true }); const context = await browser.newContext(); const page = await context.newPage();

// Go to FlashScore
await page.goto('https://www.flashscore.com/', { waitUntil: 'load' });

// Wait for cookie dialog and accept it if present
try {
    await page.waitForSelector('button:has-text("Accept")', { timeout: 5000 });
    await page.click('button:has-text("Accept")');
    console.log('Accepted cookies');
} catch (error) {
    console.log('No cookie dialog found');
}

// Wait for full page load
await page.waitForTimeout(5000);

await browser.close();

})();

